# Reference: https://github.com/codecov/support/wiki/Codecov-Yaml

coverage:
  fixes:
    - "src/generalized_lazy_search::"
  ignore:
    - "build"
    - "src/ompl"
    - "tests"

comment:
  layout: "diff, flags, files"